name: Test Time
on:
  issue_comment:
    types: [created, edited, deleted]
    if: ${{ startsWith(github.event.comment.body, '⌛ ')
      
jobs:
  hide-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Hide comment
      - uses: int128/hide-comment-action@v1
