name: Test Time
on:
  issue_comment:
    types: [created, edited, deleted]
    if: ${{ startsWith(github.event.comment.body, '⌛ ') }}
      
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT info"
