name: Test Time
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '⌛')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "info $GITHUB_CONTEXT info"
